server:
  port: 8002

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order-service
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mysql
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect