server:
  port: 8761

spring:
  application:
    name: DISCOVERY-SERVER
  zipkin:
    base-url: http://localhost:7411
  sleuth:
    sampler:
      probability: 1.0

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
  username: ${EUREKA_USERNAME:euraka}
  password: ${EUREKA_PASSWORD:password}