server:
  port: 8001

spring:
  application:
    name: PRODUCT-SERVICE
  config:
    import: "configserver:http://config-server:9091"
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: product-service
  # zipkin:
  #   base-url: http://zipkin:7411

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

# logging:
#   pattern:
#     level: [${spring.application.name:},%X{traceId:-},%X{spanId:-}]