server:
  port: 8001

spring:
  application:
    name: PRODUCT-SERVICE
  config:
    import: "optional:configserver:http://config-server:9001"
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: product-service
      
