server:
  port: 8001

spring:
  application:
    name: PRODUCT-SERVICE
  config:
    import: "configserver:http://config-server:9091"
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: product-service
  zipkin:
    base-url: http://zipkin:7411