server:
  port: 8003

spring:
  application:
    name: INVENTORY-SERVICE
  config:
    import: "configserver:http://config-server:9091"
  datasource:
    url: jdbc:postgresql://postgres:5432/inventory-service
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  zipkin:
    base-url: http://localhost:7411
  sleuth:
    sampler:
      probability: 1.0
