server:
  port: 8003

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/inventory-service
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
